### ISSUE TITLE
volume weigted macd indicator

### ISSUE THREAD

**Issue by tarantula3535** [freqtrade/technical#106]
hi i use this indicator.. anyone should helpfull.. here is the tradingview's link
https://tr.tradingview.com/script/wVe6AfGA-VOLUME-WEIGHTED-MACD-V2-VWMACDV2-BY-KIVAN%C3%87-fr3762/
```python
def vwmacd(dataframe, fastperiod=12, slowperiod=26, signalperiod=9):
# //author: KIVANC @fr3762 on twitter
# https://tr.tradingview.com/script/wVe6AfGA-VOLUME-WEIGHTED-MACD-V2-VWMACDV2-BY-KIVAN%C3%87-fr3762/
# study("VOLUME WEIGHTED MACD V2", shorttitle="VWMACDV2")
# fastperiod = input(12,title="fastperiod",type=integer,minval=1,maxval=500)
# slowperiod = input(26,title="slowperiod",type=integer,minval=1,maxval=500)
# signalperiod = input(9,title="signalperiod",type=integer,minval=1,maxval=500)
# fastMA = ema(volume*close, fastperiod)/ema(volume, fastperiod)
# slowMA = ema(volume*close, slowperiod)/ema(volume, slowperiod)
# vwmacd = fastMA - slowMA
# signal = ema(vwmacd, signalperiod)
# hist= vwmacd - signal
# plot(vwmacd, color=blue, linewidth=2)
# plot(signal, color=red, linewidth=2)
# plot(hist, color=green, linewidth=4, style=histogram)
# plot(0, color=black)
    import talib.abstract as ta
    df = dataframe.copy()
    df["fastMA"] = ta.EMA(df["volume"]*df["close"], fastperiod) / ta.EMA(df["volume"], fastperiod)
    df["slowMA"] = ta.EMA(df["volume"]*df["close"], slowperiod) / ta.EMA(df["volume"], slowperiod)
    df["vwmacd"] = df["fastMA"] - df["slowMA"]
    df["signal"] = ta.EMA(df["vwmacd"], signalperiod)
    df["hist"] = df["vwmacd"] - df["signal"]
    df = df.drop(
        columns=['fastMA', 'slowMA', 'high', 'low', 'close', 'open']
    )
#return columns vwmacd,signal,hist
    return df
```

**Comment by ozandem** [comment]
Hi tarantula3535 could you provide any information how to use this indicator in strategy?

Thank you

**Comment by tarantula3535** [comment]
hi...you can use just like macd... vmacd cross signal...
If you want to use a sample, I can send it after a few hours when it is on the pc ..

**Comment by ozandem** [comment]
It will be greatful if you could provide any sample with this indicator.

**Comment by tarantula3535** [comment]
dataframe["vwmacd"] = vwmacddf["vwmacd"]
        dataframe["signal"] = vwmacddf["signal"]

**Comment by tarantula3535** [comment]
call the library and in the populate indicators
![image](https://user-images.githubusercontent.com/63812786/94425815-353ee000-0195-11eb-8db7-14769c20976b.png)
write that code...
and whatever you want to use in the buy/sell trend cross? or >
![image](https://user-images.githubusercontent.com/63812786/94427677-23127100-0198-11eb-8a9a-ecdebca28241.png)
