### ISSUE TITLE
How to add indicators to strategy

### ISSUE THREAD

**Issue by ozandem** [freqtrade/technical#114]
Hello guys, I see lots of `def supertrend(dataframe, multiplier=3, period=10):` or `def MOST(dataframe , percent, length):` etc. but I couldnt find any guide how to implant to strategy.

**What I tried**
For example I choose this def from https://github.com/freqtrade/technical/issues/90

```
def MOST2(dataframe,  percent=2, length=8, MAtype=1):
    import talib.abstract as ta
    df = dataframe.copy()
    mostvalue = 'MOST_' + str(length) + '_' + str(percent)
    mavalue = 'MA_' + str(length) + '_' + str(percent)
    trend = 'Trend_' + str(length) + '_' + str(percent)
    # Compute basic upper and lower bands
    if MAtype==1:
        df[mavalue]=ta.EMA(df , timeperiod = length)
    elif MAtype==2:
        df[mavalue]=ta.DEMA(df , timeperiod = length)
    elif MAtype==3:
        df[mavalue]=ta.T3(df , timeperiod = length)
    df['basic_ub'] = df[mavalue] * (1+percent/100)
    df['basic_lb'] = df[mavalue] * (1-percent/100)
    # Compute final upper and lower bands
    df['final_ub'] = 0.00
    df['final_lb'] = 0.00
    for i in range(length, len(df)):
        df['final_ub'].iat[i] = df['basic_ub'].iat[i] if df['basic_ub'].iat[i] < df['final_ub'].iat[i - 1] or df[mavalue].iat[i - 1] > df['final_ub'].iat[i - 1] else df['final_ub'].iat[i - 1]
        df['final_lb'].iat[i] = df['basic_lb'].iat[i] if df['basic_lb'].iat[i] > df['final_lb'].iat[i - 1] or df[mavalue].iat[i - 1] < df['final_lb'].iat[i - 1] else df['final_lb'].iat[i - 1]
    # Set the MOST value
    df[mostvalue] = 0.00
    for i in range(length, len(df)):
        df[mostvalue].iat[i] = df['final_ub'].iat[i] if df[mostvalue].iat[i - 1] == df['final_ub'].iat[i - 1] and df[mavalue].iat[i] <= df['final_ub'].iat[i] else \
                        df['final_lb'].iat[i] if df[mostvalue].iat[i - 1] == df['final_ub'].iat[i - 1] and df[mavalue].iat[i] >  df['final_ub'].iat[i] else \
                        df['final_lb'].iat[i] if df[mostvalue].iat[i - 1] == df['final_lb'].iat[i - 1] and df[mavalue].iat[i] >= df['final_lb'].iat[i] else \
                        df['final_ub'].iat[i] if df[mostvalue].iat[i - 1] == df['final_lb'].iat[i - 1] and df[mavalue].iat[i] <  df['final_lb'].iat[i] else 0.00
    # Mark the trend direction up/down
    df[trend] = np.where((df[mostvalue] > 0.00), np.where((df[mavalue] < df[mostvalue]), 'down',  'up'), np.NaN)
    # Remove basic and final bands from the columns
    df.drop(['basic_ub', 'basic_lb', 'final_ub', 'final_lb'], inplace=True, axis=1)
    df.fillna(0, inplace=True)
    return df
```

**But I don't know how to use it and couldnt find any guide.Btw I am noob**

**Thanks for reply**

Edit: I am using plot. So it would be good if u tell me how to see this indicator result in plot. Because i want to compare with tradingview etc.

**Comment by xmatthias** [comment]
well in theory, you can just dump it into your strategy file and call this function.

Obviously how to handle the return of the function will depend on the function - to which a "general" statement is impossible to make, as every author may implement it slightly differently.

Please note that since you've found it in an issue - there's no guarantee if it's correct (according to the definition of this indicator) or wrong. Since it was posted in an issue, i guess the author assumes it's correct - but only a cross-check will tell for sure (this is in no way critique on the author of this indicator - just a general point).



Please understand that we'll not provide basic python support (how to include a function, how to call a function, how to work with the returns, ...) - so i would suggest to do a python tutorial that will teach you the basics.
There are some good ones around for working with pandas ... which should be able to get you going quite soon.

**Comment by tarantula3535** [comment]
![image](https://user-images.githubusercontent.com/63812786/94425010-d88ef580-0193-11eb-80c0-4660a516dc84.png)

**Comment by tarantula3535** [comment]
first head of the page 
![image](https://user-images.githubusercontent.com/63812786/94425069-f3fa0080-0193-11eb-949b-69272f9edbcc.png)
second in the populate indicators
![image](https://user-images.githubusercontent.com/63812786/94425033-e6447b00-0193-11eb-9292-5baabb51d04e.png)
and whichever usage you choose in the populate buy or sell trend
![image](https://user-images.githubusercontent.com/63812786/94425240-45a28b00-0194-11eb-927b-9e7473dce846.png)
i use like this..it helps ..

**Comment by ozandem** [comment]
Thank you tarantula3535 and xmatthias for sharing your knowledges. I tried tarantula3535 guide and it worked. I compare in plot and tradingview, I don't think there is a problem. When CLOSE line in the plot greater and equal MOSCTCOL line, script create buy signal.
