### ISSUE TITLE
Variable Index Dynamic Average VIDYA

### ISSUE THREAD

**Issue by tarantula3535** [freqtrade/technical#116]
https://tr.tradingview.com/script/64ynXU2e/
can anyone help write this indicator ?
it is a good filter..

**Comment by xmatthias** [comment]
I guess the following should work:
```
def VIDYA(dataframe, length=9, select=True):
    """
    select: True = CMO, False= StDev
    """
    df = dataframe.copy()
    alpha = 2 / (length + 1)
    df['momm'] = df['close'].diff()
    df['m1'] = np.where(df['momm'] >= 0, df['momm'], 0.0)
    df['m2'] = np.where(df['momm'] >= 0, 0.0, -df['momm'])
    
    df['sm1'] = df['m1'].rolling(length).sum()
    df['sm2'] = df['m2'].rolling(length).sum()
    
    df['chandeMO'] = 100 * (df['sm1'] - df['sm2']) / (df['sm1'] + df['sm2'])
    if select:
        df['k'] = abs(df['chandeMO']) / 100
    else:
        df['k'] = df['close'].rolling(length).std()
    df.fillna(0.0, inplace=True)

    df['VIDYA'] = 0.0
    for i in range(length, len(df)):
        
        df['VIDYA'].iat[i] = alpha * df['k'].iat[i] * df['close'].iat[i] + (1 - alpha * df['k'].iat[i]) * df['VIDYA'].iat[i-1]
    
    return df['VIDYA']
```

I'm no expert in pinescript though - so please help me validate this so we can add it to technical in the future.

**Comment by tarantula3535** [comment]
thanks buddy i will try and inform you about it works properly...
I hope you took a look at my other indicator posts.. 
i checked it and they are working properly
supertrend , MADR , VWMACD , RMI ... and the others.. @xmatthias

**Comment by xmatthias** [comment]
oh well, you bet (RMI + VWMACD + TKE are in #117) :+1:

**Comment by tarantula3535** [comment]
thenx man i add my indicators file...that is corrrect results...tehnk you for helping....
#117 I hope I could help..

**Comment by xmatthias** [comment]
Thanks for the feedback, added it to #117 too.

**Comment by acemi1** [comment]
hi, indicator calculation does not match tradingview.
I found a code that works correctly.
However, I am a beginner in python. I can't give you ready code.

https://github.com/freqtrade/technical/issues/97#issuecomment-954725654

**Comment by xmatthias** [comment]
well the link is for a completely different indicator (OTT) - so i'm not sure how that comment is relevant here.

**Comment by acemi1** [comment]
Thank you for the answer.
There is no error in the link. Calculating "vidya" in OTT indicator. Written as df['var'] in the code.
I took the relevant part in the code of the OTT indicator and tried to make it usable. The results are the same as with Tradindview.

`def vidya (dataframe=df, length = 4, source="close"):

    alpha = 2 / (length + 1)
    df['ud1'] = np.where(df[source] > df[source].shift(1), (df[source] - df[source].shift()), 0)
    df['dd1'] = np.where(df[source] < df[source].shift(1), (df[source].shift() - df[source]), 0)
    df['UD'] = df['ud1'].rolling(9).sum()
    df['DD'] = df['dd1'].rolling(9).sum()
    df['CMO'] = ((df['UD'] - df['DD']) / (df['UD'] + df['DD'])).fillna(0).abs()


    df['Var'] = 0.0
    for i in range(length, len(df)):
        df['Var'].iat[i] = (alpha * df['CMO'].iat[i] * df[source].iat[i]) + (1 - alpha * df['CMO'].iat[i]) * \
                           df['Var'].iat[
                               i - 1]
    # print("vidya indicator\n", df['Var'])
    return df['Var']

vidya ()`

**Comment by xmatthias** [comment]
If you think an indicator is wrong and you have a fix, please open a pull request submitting the fix (please with sample code/screenshots showing missalignment / new alignment with tradingview).

Please understand that i'll not be extracting code from issue comments - which will have me repeat the work you already did (compare it with tradingview, ...).
