### ISSUE TITLE
Pivot points

### ISSUE THREAD

**Issue by aescsa2** [freqtrade/technical#127]
Hello I have got a problem trying to implement de Pivot Points Indicator, first of all sorry for my english.

Now, as we can see in trading view, the Indicator takes a value for R1, R2, R3, S1, S2, S3,... thats remains unchanged for a number of periods, for instance in this chart of 5 minutes timeframe (less than 15 minutes),  is changed DAILY, is well explained in this link ''https://www.tradingview.com/support/solutions/43000521824-pivot-points-standard/''.
![trading view](https://user-images.githubusercontent.com/72233354/98261370-ae93d480-1f84-11eb-9c1b-066f8b127e2b.png)

In my strategy, as a sell order I coded that, when the price close is above R2 its has to sell, the wierd thing is that almost always is selling even when the price is below R2 value, so I printed the value that the BOT was calculating for R2, and as we can see in this ADA/USDT chart the value for R2 was 0.10310 on 30 Oct 16:30, but the value that BOT was getting for R2  at that the exact time and exact date was 0.092989.
![valor r2](https://user-images.githubusercontent.com/72233354/98262903-6ecdec80-1f86-11eb-8481-f573f6918dde.png)
![valor r2 en bot](https://user-images.githubusercontent.com/72233354/98262937-78efeb00-1f86-11eb-866a-62ba451edced.png)

Also as I said before, the value for each suport and resistance level sould stay unchanged for 1 day, on every chart that is below 15min timeframes,  and in the print of the dataframe.loc, the value for R2 is changed every 5 minutes, so it makes no sense for me, its not a support level anymore is more like a moving average.

Here is my code, hope you can help me, just to know if I did something wrong or for you to know if something must be fixed in the code of the indicator, thanks for your time.
 
![pivots 1](https://user-images.githubusercontent.com/72233354/98264195-f23c0d80-1f87-11eb-8e9e-2392a1dbb96e.png)
![pivots 2](https://user-images.githubusercontent.com/72233354/98264199-f49e6780-1f87-11eb-8e02-2f632617f8a7.png)
![pivots 3](https://user-images.githubusercontent.com/72233354/98264790-91610500-1f88-11eb-87f8-0889ac31f0bf.png)

**Comment by xmatthias** [comment]
This indicator will not do "daily" at the moment - but will use a rolling approach.

You can make it use a rolling of 1d (timeperiod parameter) - but then it'll be windows from 00:00-24:00, 1:00 - 0:59, ... 

---

additional note: 
I don't think the "daily" approach is suitable for crypto anyway - that's made for traditional markets, which have a daily open time - where "daily" is really relevant, as it has a meaning for the market cycle.

Crypto markets however are "always open" - so if you'd use  "daily" windows (like in the screenshot above)- which timezone will you use for crypto markets, which are always open? 

Your own (for convenience)? UTC? or maybe US, or Asia, or some random European timezone?

Therefore, using a rolling daily parameter (as this indicator is doing) is actually a better approach in my opinion.

Now that does not mean it cannot be changed to also do the "batched daily" - but it's currently not implemented - and i don't think that for the forseeable future, i'll have time (nor will) to implement this - so if you' think it's a must, i'd encourage doing a Pull request adding this feature.

**Comment by aescsa2** [comment]
I agree you, but anyways the problem might be almost solved using weekly changes for the suports and resistance values I guess, there would be a problem of just hours on every last day of the week?, Hope you excuse me about my inexperience, but how could I use those week timeframes for the calculations of the indicator, to keep those supports and resistances values unchanged, and still be using 5 minute charts for my trading? Thanks again for your time :)

**Comment by xmatthias** [comment]
you can't really use weekly candles with 5m candles - it's too long, so after ~3 days, your weekly candle doesn't have an overlapping candle to join to the 500 5m candles.

However, using weekly candles is NOT what tradingview talks about, but about daily candles (where the described method works fine).

You should be able to repurpose parts of [this](https://www.freqtrade.io/en/latest/strategy-customization/#complete-data-provider-sample) sample - obviously with a lot of changes to actually get pivot points instead of RSI as shown there.

Best plot the results afterwards (`freqtrade plot-dataframe`) - so you see what you'll get.

**Comment by MichaelMacca96** [comment]
Hi xmatthias,

I Implemented the pivots_points function and as you suggested, I 
".....try using informative pair (same pair, '1d' resolution) - calculate the pivot point on that and then merge back to the original dataframe - that should get you exactly what you need....."

It works but after a few hours, the Pivots Lines on FreqUI disappear!

I'm working with a timeframe of 1m and I want, if possible, to have the Pivots_point on a 1d resolution.

Thanks!

Best Regards!

**Comment by xmatthias** [comment]
Merging assumes that at least one common time is available.
That's not the case between 1m  and 1d, as the 2 are too far apart (you get 1000 1m candles, which will not give you a 00:00 candle in the last part of the day).

i doubt this makes sense though - if you look at 1d data, you'll not need signals at the 1m timeframe (which is usually way too noisy to get good signals out anyway) - so best consider switching to a slightly bigger timeframe like 5m or 15m.

**Comment by MichaelMacca96** [comment]
Perfect! Thank you for your help!
