### ISSUE TITLE
Wrong method documentation in method segtrends

### ISSUE THREAD

**Issue by baont** [freqtrade/technical#130]
In method segtrends, trendline.py.
These params are listed in comment section but do not exist actual parameters:

    :param x: One-dimensional data set
    :param window: How long the trendlines should be. If window < 1, then it
                   will be taken as a percentage of the size of the data

Whereas, param segments=2 is not documented.

**Comment by xmatthias** [comment]
you're correct, seems like the docstring was copy/pasted but not properly fixed...

**Comment by xmatthias** [comment]
Now while this is now corrected, i'd urge caution with this.

Playing with it quickly, i think this indicator will need to be fed with rolling data to avoid lookahead bias during backtesting, as it seems to be using the full dataset provided.

You can best check this graphically with `charts=True` - which seems to generate just one trendline for the whole period.
