### ISSUE TITLE
ATR is calculated wrongly and is extremely

### ISSUE THREAD

**Issue by baont** [freqtrade/technical#135]
Base on this article https://www.investopedia.com/terms/a/atr.asp. The way atr is calculated is wrong because it only takes into account 'close' but leave out 'high', 'low'. Beside, when tested, this method runs extremely slow with little data.

**Comment by xmatthias** [comment]
there's another issue where this is discussed in the strategy repo: https://github.com/freqtrade/freqtrade-strategies/issues/30

Feel free to improve performance (but honestly, you'll have problems with that i'll think).
The way ATR is calculated requires a loop (current value is based on the result of  the same calculation for the previous value).

Every indicator that requires a loop will automatically be a lot slower than any indicator that can be vectorized (calculated in one go across the whole timerange) - and there is very little possibility to optimize these calls.

That said, i just noticed that we have 2 different calculations of atr:
one in `volatility.py` (this will most likely be wrong as it seems to only use close - but uses the `average_true_range` directly from pyti - so having that fixed would require an issue against the pyti repository.

The second version is in indicators (which is vendored from qtpylib). At first glance, the calculation seems ... better aligned to investopedia ... 

however please investigate in the linked issue above, as i think also this calculation does not match with tradingview (however i don't see tradingview as gold standard, maybe their implementation is wrong).

**Comment by baont** [comment]
well i found this code on stackoverflow [https://stackoverflow.com/questions/40256338/calculating-average-true-range-atr-on-ohlc-data-with-python](url) and tested myself
`def wwma(values, n):
    """
     J. Welles Wilder's EMA 
    """
    return values.ewm(alpha=1/n, adjust=False).mean()

def atr(df, n=14):
    data = df.copy()
    high = data[HIGH]
    low = data[LOW]
    close = data[CLOSE]
    data['tr0'] = abs(high - low)
    data['tr1'] = abs(high - close.shift())
    data['tr2'] = abs(low - close.shift())
    tr = data[['tr0', 'tr1', 'tr2']].max(axis=1)
    atr = wwma(tr, n)
    return atr`
It's extremely extremely extremely fast

**Comment by xmatthias** [comment]
it might be fast - but it's most likely not aligned to the calculation of investopedia - which does not mention the use of Wilders MA at all.

You can also use `from technical.vendor.qtpylib.indicators import atr` - which will also be extremely fast (as said, it's in technical twice for no real reason)

**Comment by baont** [comment]
i could change to values.rolling(14).mean(). Haven't tested it yet

**Comment by xmatthias** [comment]
as said, technical does contain an implementation of atr already, which is fast. 
I'll remove the pyti mapper so it'll be clear which one to use.
