### ISSUE TITLE
Looking for Laguerre Rsi Indicator

### ISSUE THREAD

**Issue by mehdico** [freqtrade/technical#150]
Hey guys,

I'm wondering how can I find a Laguerre Rsi indicator for Freqtrade. I've found one in backtrader (https://github.com/mementum/backtrader/blob/master/backtrader/indicators/lrsi.py) but I can't use it.

I've tried to use this but failed:

`

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
      
      try:
         dataframe['l0_1'] = dataframe['l0']
         dataframe['l1_1'] = dataframe['l1']
         dataframe['l2_1'] = dataframe['l2']
         dataframe['l3_1'] = dataframe['l3']
         dataframe['l0'] = dataframe['l0'] = (1.0 - gamma) * dataframe['close'] + gamma * dataframe['l0_1']
         dataframe['l1'] = dataframe['l1'] = -gamma * dataframe['l0'] + dataframe['l0_1'] + gamma * dataframe['l1_1']
         dataframe['l2'] = dataframe['l2'] = -gamma * dataframe['l1'] + dataframe['l1_1'] + gamma * dataframe['l2_1']
         dataframe['l3'] = dataframe['l3'] = -gamma * dataframe['l2'] + dataframe['l2_1'] + gamma * dataframe['l3']

         cu = 0.0
         cd = 0.0
         if dataframe['l0'] >= dataframe['l1']:
            cu = dataframe['l0'] - dataframe['l1']
         else:
            cd = dataframe['l1'] - dataframe['l0']

         if dataframe['l1'] >= dataframe['l2']:
            cu += dataframe['l1'] - dataframe['l2']
         else:
            cd += dataframe['l2'] - dataframe['l1']

         if dataframe['l2'] >= dataframe['l3']:
            cu += dataframe['l2'] - dataframe['l3']
         else:
            cd += dataframe['l3'] - dataframe['l2']

         den = cu + cd
         dataframe['lrsi'] = 1.0 if not den else cu / den
      except:
         dataframe['l0'] = 0.0
         dataframe['l1'] = 0.0
         dataframe['l2'] = 0.0
         dataframe['l3'] = 0.0
         dataframe['l0_1'] = 0.0
         dataframe['l1_1'] = 0.0
         dataframe['l2_1'] = 0.0
         dataframe['l3_1'] = 0.0
         dataframe['lrsi'] = 0

      print('rsi is')
      print(dataframe['lrsi'])
      
      return dataframe

`

Any suggestion?
Thanks.

**Comment by boschje** [comment]
Laguerre RSI is already included in freqtrade technical library: https://github.com/freqtrade/technical/blob/d26c4804e1f4af010cadc83db8b23cbcebfc28cc/technical/indicators/indicators.py#L77

You do need to install this technical library: https://github.com/freqtrade/technical#usage, or when using Docker you can build the image with this file: https://github.com/freqtrade/freqtrade/blob/develop/docker/Dockerfile.technical

Then in your strategy import the indicator:
`from technical.indicators import laguerre`

And then define your indicator:
`dataframe['lrsi'] = laguerre(dataframe, gamma=0.75, smooth=1, debug=False)`

**Comment by xmatthias** [comment]
The above answers this quite nicely i think, thanks @boschje :+1: 

Just use what's given, no need to reinvent the wheel ... 

I'll close this for now, feel free to comment below or reopen if this is still unclear.
