### ISSUE TITLE
Calculation of Heikin-Ashi open

### ISSUE THREAD

**Issue by boschje** [freqtrade/technical#152]
I am comparing the Heikin-Ashi candles from freqtrade technical library with QTPyLib, and found a difference in the calculation of the first candle open. Since all following candles are based on the previous, it affects the Heikin-Ashi open value for all candles in the dataframe.

Normally Heikin-Ashi open is based on the previous candle: `(open.shift(1) + close.shift(1)) / 2`

However for the first candle we should use the current candle: `(open + close) / 2`

Reference: https://school.stockcharts.com/doku.php?id=chart_analysis:heikin_ashi
"The first Heikin-Ashi open equals the average of the open and close ((O+C)/2)."

But currently in freqtrade technical only the open is used for the first candle: 
https://github.com/freqtrade/technical/blob/d26c4804e1f4af010cadc83db8b23cbcebfc28cc/technical/candles.py#L12

Suggest to change this to:  
`bars.loc[:1, 'ha_open'] = (bars['open'].values[0] + bars['close'].values[0]) / 2`

Then it would be same as QTPyLib and Tradingview.

**Comment by xmatthias** [comment]
i'm pretty open to pull requests in this regards ;) especially if it's that well researched :+1:

**Comment by boschje** [comment]
Done 👍  A few more changes were needed, see pull request for details: https://github.com/freqtrade/technical/pull/154

**Comment by xmatthias** [comment]
one thing to point out:
relying on qtpylib for your benchmarks is a VERY dangerous approach, as they have quite a few indicators wrong / not according to spec.

I'm not certain about haikin-ashi in particular - just pointing this out "in general".
I know freqtrade vendors qtpylib - that's mainly for historical reasons - "today", i'd probably not do that again...

**Comment by boschje** [comment]
Yes, I am aware. I recently compared RSI and some moving averages between finta, talib, and qtpylib. And spotted differences in all of them...

**Comment by xmatthias** [comment]
closed by #154 
Thanks for fixing this! 👍
