### ISSUE TITLE
[improvment] including an external library

### ISSUE THREAD

**Issue by Pascal66** [freqtrade/technical#155]
tapy library https://pandastechindicators.readthedocs.io/en/latest/ https://github.com/dmitriiweb/tapy
wich extend indicators can be usefull as it work like qtpylib does
not enough skill to use it or integrate it

**Comment by Pascal66** [comment]
The only problem is the redefinition of column index
ie Close->close, High->high and so on

**Comment by xmatthias** [comment]
I don't see why we should integrate this into technical (i know we wrap other libraries, but i don't like that fact either, and it will probably be removed sometime in the future - with the link to use the original library directly).

If you want to use it in the strategy, you can install that for your environment and import it in the strategy directly - and also use it from there directly.

For the column names, it seems like you can pass this in as parameters. I guess that will be documented as well ... 

https://github.com/dmitriiweb/tapy/blob/492044cb75f9cd63a6fc78748104f72f9e27bce2/tapy/indicators.py#L31-L58

**Comment by Pascal66** [comment]
I know this is enough documented. I proposed a PR. btw, this seems not followed by the author.
I've just not enough skill to init this library with the column names of freqtrade
I already use it as external library in my strategies. but limited by the index names of column.
And why I ask that is because qtpylib us the same structure, and just want to extend it

**Comment by xmatthias** [comment]
qtpylib is slightly different, as the library itself has quite heavy dependencies (QT) - which we don't use, therefore only the qtpylib indicators file is "vendored" - which means it's a 1:1 copy of what qtpylib has.

This approach will however not make sense for this library, as it's a pure technical library, with only the dependencies that are needed.

based on the docs, you should be able to use something like the following:

``` python
from tapy import Indicators
...

indicators = Indicators(dataframe, open_col="open", high_col="high", low_col="low", close_col="close", volume_col="volume" )

indicators.accelerator_oscillator(column_name='AC')

# Not sure this is needed ... but most likely yes
# dataframe = indicators.df
# alternatively, return the dataframe directly
# return indicators.df

```

**Comment by Pascal66** [comment]
Thank you for your time.
That's what I done, unfornatly this doesnt work for some indicators, maybe coded on the fly.
Just using it for allogator and smma, will try to do that manually
