### ISSUE TITLE
Plotting or using the future parts of senkou_span_a/b

### ISSUE THREAD

**Issue by epigramx** [freqtrade/technical#161]
![image](https://user-images.githubusercontent.com/2960257/108682742-5c59cd80-74f9-11eb-9545-38aedd00918f.png)
As you can see on a current price chart here: the default behavior of senkou_span_a and b is to be plotted into the future (without the need of future price data!). 

However I noticed that freqtrade plots only up to the current price and cuts off the parts of senkou_span_a and b that are in the future.

I wonder if we can plot those parts and most importantly: if we can use the shifted (future) parts of them in strategies.

**Comment by epigramx** [comment]
I realized this has been addressed, in #82. Living this open for a while in case someone wants to comment on that freqtrade doesn't literally plot it shifted forward too but I find it unimportant so I'll close it soon.

**Comment by xmatthias** [comment]
well in theory you can plot the "forward-shifted" version - but it'll be cutoff for the future candles.

i think i'll close this now however, as i don't see a point in leaving issues open forever to show people things (that would lead to 1000 open issues, where noone will even try to search anymore).
