### ISSUE TITLE
How to use "Madrid Trend Squeeze"

### ISSUE THREAD

**Issue by MrHumanRebel** [freqtrade/technical#173]
Hi!

I have been peeking into the "Madrid Trend Squeeze" trade indicator, and I would really like to implement it in my strategy, but I really don't know how to start at all. How to call this indicator in the lib section / populate indicators / buy and sell trend. I'am clueless for now, can someone help me out? These technical indicators are really good, but frankly I don't know the way how to implement any of them, especially the "Madrid Trend Squeeze".
Thanks for any help!

**Comment by xmatthias** [comment]
I'm not 100% sure what you'd expect ...

basic usage will be as follows (it returns a tuple with 3 values).

``` python
sqz_cma_c, sqz_rma_c, sqz_sma_c = madrid_sqz(dataframe, length=34, ...)
dataframe['sqz_cma_c'] = sqz_cma_c
dataframe['sqz_rma_c'] = sqz_rma_c
dataframe['sqz_sma_c '] = sqz_sma_c 
```

it'll return different colors (yellow, green, maroon, ...).

how to trade this indicator is a different topic - i've never used it so i can't tell you, but i think the tradingview link in the readme.md should have some helpful information in that regard.
