### ISSUE TITLE
docker installation problem

### ISSUE THREAD

**Issue by pamben** [freqtrade/technical#177]
Hi

I am using docker-compose and it works without any problem. Now, I want to add technical to the default image but I got error during the build

This is my  Dockerfile.technical file:

`ROM freqtradeorg/freqtrade:develop

RUN apt-get update \
    && apt-get -y install git \
    && apt-get clean \
    && pip install git+https://github.com/freqtrade/technical`

and this is my docker-compose:

`version: '3'
services:
  freqtrade:
    #image: freqtradeorg/freqtrade:stable
    image: freqtradeorg/freqtrade:custom
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./Dockerfile.technical"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
    # before enabling this.
    # ports:
    #   - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
`

then I build the image by `docker-compose build`

Unfortunately, I got the following error:

`Building freqtrade
Sending build context to Docker daemon  3.584kB

Step 1/2 : FROM freqtradeorg/freqtrade:develop
 ---> 8621fb14095f
Step 2/2 : RUN apt-get update     && apt-get -y install git     && apt-get clean     && pip install git+https://github.com/freqtrade/technical
 ---> Running in facf971d95e8
Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
The command '/bin/sh -c apt-get update     && apt-get -y install git     && apt-get clean     && pip install git+https://github.com/freqtrade/technical' returned a non-zero code: 100
ERROR: Service 'freqtrade' failed to build`

I built the image with Sudo and directly with root, and it is not working. 

I added sudo before apt-get but It shows me the following message and again it didn't work:

`Step 1/2 : FROM freqtradeorg/freqtrade:develop
 ---> 8621fb14095f
Step 2/2 : RUN sudo apt-get update     && sudo apt-get -y install git     && sudo apt-get clean     && sudo pip install git+https://github.com/freqtrade/technical
 ---> Running in 0bd9fb6352b4

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
The command '/bin/sh -c sudo apt-get update     && sudo apt-get -y install git     && sudo apt-get clean     && sudo pip install git+https://github.com/freqtrade/technical' returned a non-zero code: 1
ERROR: Service 'freqtrade' failed to build`

I edited visudo for specific user to run sudo without password to solve sudo: no tty present and no askpass program specified message but nothing changed.

what is my mistake and how to solve it?

Thanks

**Comment by xmatthias** [comment]
the new develop image is now no longer using root as user, but a lower privileges user.

At the same time however, it includes the latest technical release - and you therefore do not need to build the image yourself anymore, simply using the develop image will suffice.

**Comment by pamben** [comment]
Thanks for your help.

freqtrade should keep documents update to prevent confusion.

**Comment by xmatthias** [comment]
The documentation is uptodate, but it'll depend on the version of the documentation you're looking at (stable / develop/ ...).
