### ISSUE TITLE
Please nerd help importing custom indicator

### ISSUE THREAD

**Issue by nerd12** [freqtrade/technical#199]
I followed ichimoku example and it worked however, I can't install pivot points, trendlines and zlema. Could you please show me some code examples, I know it must be just a matter of correct naming.

**Comment by xmatthias** [comment]
I do not see how this issue differs from https://github.com/freqtrade/freqtrade/issues/5074.

As explained there - your imports were wrong, and most likely, this didn't change if it doesn't work.

Please note:
This is an open source project - which means people spend their time trying to move the project forward, as well as supporting people.
As such - i do have the expectation that users will put in some time to research how to do things themselfs, and will not be writing the strategy (doing the work) for users.

Questions with "please code this for me" - which show that you probably didn't really put time into it (otherwise you'd have a starting point)  will not be helped / supported.
Thanks for your understanding.

---

If you're having problems with a particular part - please post what you got so far (in a reproducible manner, not parts of the code) - so we can see where you went wrong and try to assists.

**Comment by nerd12** [comment]
> If you're having problems with a particular part - please post what you got so far (in a reproducible manner, not parts of the code) - so we can see where you went wrong and try to assists.

This is basically what I'm trying to do, in the first part I import all the libs, at the end of the code block I'm import the custom modules: 

`# --- Do not remove these libs ---
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame

from freqtrade.strategy import IStrategy, merge_informative_pair # informative pair
from freqtrade.strategy import CategoricalParameter, DecimalParameter, IntParameter

import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib

# Import Custom

from technical import trendline
from technical import pivots_points
from technical.indicators import ichimoku
from technical.indicators import zema
from technical.util import resample_to_interval, resampled_merge`


Then I try to call them:

`        dataframe['trend'] = trendline(dataframe)

        dataframe['pivot'] = pivots_points(dataframe)

        dataframe['zema'] = zema(dataframe)

        ichi = ichimoku(dataframe)
        dataframe['tenkan'] = ichi['tenkan_sen']
        dataframe['kijun'] = ichi['kijun_sen']
        dataframe['senkou_a'] = ichi['senkou_span_a']
        dataframe['senkou_b'] = ichi['senkou_span_b']
        dataframe['cloud_green'] = ichi['cloud_green']
        dataframe['cloud_red'] = ichi['cloud_red']`

I know there must be something wrong in the naming. I'm getting a grasp of programming through freqtrade, never programmed before prior the last month, started using atom and then jupyter, wrote my first strategy. The problem must be something easy, though I have no idea.

**Comment by xmatthias** [comment]
The way you import trendline (for example) - makes trendline a package, not a function - as such, you can't call it directly.

You might use `trendline.segtrends()` or similar for this ... 
but as mentioned before (somewhere) - i'd advise NOT to use trendlines - as this will not be backtestable as it has a strong lookahead bias by using all the available data for the calculation.

For pivotpoints it's similar - you can either change the import to `from technical.pivot_points import pivot_points` - or leave the import as is and use `pivots_points.pivots_points()` to call it.

**Comment by nerd12** [comment]
I imported pivots:
`from technical.pivots_points import pivots_points`

Now I'm trying to call it like this, under "pupulate indicators":
`dataframe['pivot'] = pivots_points.pivots_points(dataframe)`

it outputs:
```
dataframe['pivot'] = pivots_points.pivots_points(dataframe)
AttributeError: 'function' object has no attribute 'pivots_points'
```

This means that, or I'm using the wrong naming, or I'm calling it under the wrong function right?

**Comment by xmatthias** [comment]
It was an or ... Either change the import, OR change the way you call it.
Changing both will not work.

**Comment by nerd12** [comment]
> It was an or ... Either change the import, OR change the way you call it.
> Changing both will not work.

The import must be right. How do I call it properly though? And, is it right to call it inside the "populate indicator" function? Sorry I'm a total noob.

**Comment by nerd12** [comment]
> It was an or ... Either change the import, OR change the way you call it.
> Changing both will not work.

Wait, pivots_point has at least two elements so it must be called like macd or stochastich, I try myself as I get home

**Comment by nerd12** [comment]
> The way you import trendline (for example) - makes trendline a package, not a function - as such, you can't call it directly.
> 
> You might use `trendline.segtrends()` or similar for this ...
> but as mentioned before (somewhere) - i'd advise NOT to use trendlines - as this will not be backtestable as it has a strong lookahead bias by using all the available data for the calculation.
> 
> For pivotpoints it's similar - you can either change the import to `from technical.pivot_points import pivot_points` - or leave the import as is and use `pivots_points.pivots_points()` to call it.

Could you just tell me how do I call correclty pivots_points after importing it? Thank you.

**Comment by xmatthias** [comment]
you can use this:

```
from technical.pivots_points import pivots_points

... 
# Do not overwrite dataframe directly)
df = pivot_points(dataframe)
```

there's 2 optional parameters `timeperiod=30, levels=3` .... which define how many columns you'll get (they'll be named s1-s(levels) and r1-r(levels).
