### ISSUE TITLE
Error when backtesting vwma imported from technical library - seems to be timeperiod related in populate indicators

### ISSUE THREAD

**Issue by thatyoubruce** [freqtrade/technical#226]
Thanks so much for developing and maintaining freqtrade!

I've been able to call indicators from TA-Lib for other strategies and have success with EMA in backtesting.

I'm now trying to use the technical library to import volume weighted moving average (VWMA) in the custom indicators section but having issues with vwma during backtesting - logs seem to be fine with the import.

Specific lib: 
from technical.indicators import vwma

populate_indicators:
dataframe['vwma50'] =  vwma(dataframe,timeperiod=50)

Error msg:
2021-11-22 22:25:07,695 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 54, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 655, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 610, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
  File "/freqtrade/freqtrade/strategy/interface.py", line 822, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 822, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
  File "/freqtrade/freqtrade/strategy/interface.py", line 845, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
  File "/freqtrade/user_data/strategies/vwmasma3dtest.py", line 129, in populate_indicators
    dataframe['vwma50'] =  vwma(dataframe,timeperiod=50)
**TypeError: vwma() got an unexpected keyword argument 'timeperiod'**

Looks to be something to do with timeperiod. I viewed another issue https://github.com/freqtrade/technical/issues/199 to try and see how to import vwma (I also tried volume_weighted_moving_average).

Any assistance would be much appreciate and happy to provide any further information you require.

Thanks!

**Comment by xmatthias** [comment]
I would think that `timeperiod=50` is the wrong argument for this method.

try `window` ... 

https://github.com/freqtrade/technical/blob/39db92e9ce1829cbf17391e52c85fb2bde6d0967/technical/indicators/overlap_studies.py#L85

Note: I'm aware that this is terribly misaligned throughout technical - but changing it would mean break everyone's strategies, so it's not an easy task to do.

**Comment by thatyoubruce** [comment]
Thank you for your prompt response and assistance.

The information has helped and I was able to use window instead of timeperiod.

I do agree with the technical library but I now understand a little more of how to define and call a function so hopefully it will work for the others like zema and Volume Weighted MACD :)

Thanks again for your help!

**Comment by xmatthias** [comment]
you can usually simply use code completion in editors (like vscode) to see the proper parameters for each function.
