### ISSUE TITLE
SSL channel indicator implementation in strategy

### ISSUE THREAD

**Issue by straj-granicy** [freqtrade/technical#229]
Hello everyone,
Now I'm working on strategy with SSL channel in strategy.
I found that it's been already implemented in Freqtrade, but the question is how to to implement it in strategy file.
I found that there's already been such topic
https://github.com/freqtrade/technical/issues/114
And 2 approaches were proposed.
1. to insert the code of the function in the strategy.
2. to load it from technical.indicators.

So the questions are:
1. if we use the first approach, should we insert the code of function in populate indicators like this:

```
def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
def SSLChannels(dataframe, length=10, mode="sma"):
            """
            Source: https://www.tradingview.com/script/xzIoaIJC-SSL-channel/
            Author: xmatthias
            Pinescript Author: ErwinBeckers
            SSL Channels.
            Average over highs and lows form a channel - lines "flip" when close crosses
            either of the 2 lines.
            Trading ideas:
            * Channel cross
            * as confirmation based on up > down for long
            Usage:
            dataframe['sslDown'], dataframe['sslUp'] = SSLChannels(dataframe, 10)
            """
            if mode not in ("sma"):
                raise ValueError(f"Mode {mode} not supported yet")

            df = dataframe.copy()

            if mode == "sma":
                df["smaHigh"] = df["high"].rolling(length).mean()
                df["smaLow"] = df["low"].rolling(length).mean()

            df["hlv"] = np.where(
            df["close"] > df["smaHigh"], 1, np.where(df["close"] < df["smaLow"], -1, np.NAN)
    )
            df["hlv"] = df["hlv"].ffill()

            df["sslDown"] = np.where(df["hlv"] < 0, df["smaHigh"], df["smaLow"])
            df["sslUp"] = np.where(df["hlv"] < 0, df["smaLow"], df["smaHigh"])

            return df["sslDown"], df["sslUp"]
```
The function returns 2 dataframes. But how to use them further?
Should I something like this?
dataframe['sslDown'] = df["sslDown"]
dataframe['sslUp"] = df["sslUp""]

And then to use new dataframes in populate sell and buy indicators?

2. If to use the second approach, should it be in this way?

from technical indicators import SSLchannels (is the name of indicator, which we should import the same as the name of function? or it differs?)
In populate indicators:
length=10 
mode="sma"
Should we mention there the arguments of functions?
What else should be mentioned? Frankly speaking, a liitle bit confused what to do here.

I also would be grateful if you can outline the general logic how to implement custom indicators, which are already implemented in technical indicators (https://github.com/freqtrade/technical/blob/master/technical/indicators/indicators.py) in freqtrade strategy.

The second important question to me is the general logic of creating new indicators (e.g. there're some very interesting indicators on Tradingview), so this information would be useful.
By logic I mean what should be done step by step? 
E.g. to create a function in Python. then in what file should this function should be added? What should be done next?

Really appeciate you help, advises and assistance.

Thank you in advance.

**Comment by xmatthias** [comment]
Copying a function that can also be loaded from a library is pointless. 
While you can do it (it's your code / strategy) - please don't expect support for that.

In general, i'd say it's pretty simple and you can use something like the below

``` python
from technical.indicators import SSLchannels

# ...

down, up = SSLChannels(dataframe, length=10, mode="sma")
dataframe['ssldown'] = down
dataframe['sslup'] = up
```

Now the parameters may vary by method - as different indicators will have different options. We try to document them in docstrings, so a proper installation / IDE like vscode (if setup properly) should allow you to use code completion to inspect the function arguments.

It'll be the same for new indicators, really - you simply define a method, pass in a dataframe, and implement whatever logic you think is necessary.
In general, you're probably fastest by creating the method in a jupyter notebook, where you can quickly iterate until the results are correct.
The details will again vary quite heavily by indicator - and can therefore not easily be generalized.

Once done (and you'd like to contribute the indicator) - then one of the files in `technical.indicators` will for sure be a good option.

**Comment by straj-granicy** [comment]
> Copying a function that can also be loaded from a library is pointless. While you can do it (it's your code / strategy) - please don't expect support for that.
> 
> In general, i'd say it's pretty simple and you can use something like the below
> 
> ```python
> from technical.indicators import SSLchannels
> 
> # ...
> 
> down, up = SSLChannels(dataframe, length=10, mode="sma")
> dataframe['ssldown'] = down
> dataframe['sslup'] = up
> # Alternative way:
> dataframe['sslDown'], dataframe['sslUp'] = SSLChannels(dataframe, 10)
> ```
> 
> Now the parameters may vary by method - as different indicators will have different options. We try to document them in docstrings, so a proper installation / IDE like vscode (if setup properly) should allow you to use code completion to inspect the function arguments.
> 
> It'll be the same for new indicators, really - you simply define a method, pass in a dataframe, and implement whatever logic you think is necessary. In general, you're probably fastest by creating the method in a jupyter notebook, where you can quickly iterate until the results are correct. The details will again vary quite heavily by indicator - and can therefore not easily be generalized.
> 
> Once done (and you'd like to contribute the indicator) - then one of the files in `technical.indicators` will for sure be a good option.

Hi, Matthias,
Thanks for feedback.
The alternative way looks much prettier to me
dataframe['sslDown'], dataframe['sslUp'] = SSLChannels(dataframe, 10)
But is it the argument "mode="sma" missed?
And also how can I use EMA, HMA or WMA instead of SMA?
And to conclude what was suggested by you (general logic of implementation):
In order to implement the indicator in strategy we need:
1. Import it from technical.indicators, using the name of the function.
2. Assign to new dataframes, which we want to use in populate buy&sell trends the indicator with the arguments, which is used in the function, e g.
dataframe['sslDown'], dataframe['sslUp'] = SSLChannels(dataframe, 10).

Please advise if I understood you correctly.
Thanks a lot for your assistance.

**Comment by xmatthias** [comment]
> But is it the argument "mode="sma" missed? 

Please use the search engine of your choice to investigate python default arguments.
It's not missed, but it's not necessary as sma is the default argument.

**Comment by straj-granicy** [comment]
> > But is it the argument "mode="sma" missed?
> 
> Please use the search engine of your choice to investigate python default arguments. It's not missed, but it's not necessary as sma is the default argument.

Okay, noted.
What about changing sma to other moving averages (EMA,HMA,VMA)? Is it possible?

**Comment by xmatthias** [comment]
Based on the implementation, this is currently not possible:

https://github.com/freqtrade/technical/blob/5e7e88fb8ab37ab09f60d464da96d84d3d88e1ea/technical/indicators/indicators.py#L1074-L1075

**Comment by mahammadhaneef123** [comment]
This working good. Thank You
