### ISSUE TITLE
Port Choppiness Index

### ISSUE THREAD

**Issue by Dante2333** [freqtrade/technical#25]
Chop index description:
https://www.tradingview.com/wiki/Choppiness_Index_(CHOP)
Python implementation:
https://qiita.com/hoshitter1/items/d241cd2d13b72df9a204

I tried adding choppiness.py and import it to my strategy for freqtrader but I keep getting Impossible to load strategy, this class does not exist or contains python code errors.

Any guidance on doing this my self would be great.

**Comment by xmatthias** [comment]
best look [here](https://github.com/freqtrade/technical/blob/master/technical/indicators.py) for some samples and try to do a PR with it, and we'll try to support.

the python implementation seems ... slowish as the formula doesn't look like it'll need looping, but "just" a multistep calculation (but i could be mistaking ...)

side note: your best friends will be `dataframe['atr'].rolling(n).xxx` ... ;)

**Comment by hroff-1902** [comment]
let's wait for reply from qtpylib first...

**Comment by Dante2333** [comment]
Ported by qtpylib.
