### ISSUE TITLE
resampled_merge not merging as it should

### ISSUE THREAD

**Issue by m0khtar** [freqtrade/technical#250]
Hi,
Not sure if this is an issue.

- I'm running strategy on a 30m timeframe (ETH/USDT)
- I'm doing a resample to 1d in order to calculate the pivot point ( works )
- resampled_merge is not merging as it should

`df_1d = resample_to_interval(dataframe, 1440)`
`df_1d['pivot'] = (df_1d['high'].shift() + df_1d['low'].shift() + df_1d['close'].shift()) / 3`
`dataframe = resampled_merge(dataframe, df_1d)`

![image](https://user-images.githubusercontent.com/621776/153929305-3c93f9e4-0c15-400d-97af-7bf98c925848.png)

The pivot point in the merged dataframe should be:

- Feb 14: 2887.41
- Feb 13: 2921.05

Thanks !

**Comment by xmatthias** [comment]
All dates you're looking at are candle open dates.

This means, a 30m candle that's opening at at 14 00:00 will close at 14 00:30 - so the only available closed candle is the one from the 13th.
Merging it differently would lead to a lookahead bias, as you'd be using data from 14 23:00 at 14 00:30.

As such, from the screenshot (looking at 2 date columns) - the merge looks correct, merging the 1d candle from the 13th to the 30m candle from 13th, 23:30 (both of these candles close at the same time).

**Comment by m0khtar** [comment]
@xmatthias Thanks for the clarification!
