### ISSUE TITLE
Ssl Chanel

### ISSUE THREAD

**Issue by mardrake** [freqtrade/technical#264]
Hello, how to use ssl Chanel to data frame y finance for example. And how to add library. Thanks. Tell me if there is any instructions

**Comment by xmatthias** [comment]
General usage guidance on technical (how to install, ...) can be found in this repository's [readme file](https://github.com/freqtrade/technical).

Guidance on how to use indicators can usually be found in the indicator docstring (should also be shown on any good editor if configured properly).

For SSL - you can find this here:
https://github.com/freqtrade/technical/blob/367142a8a0c61d93a5498b85040138e8c835393a/technical/indicators/indicators.py#L1058-L1073
