### ISSUE TITLE
fix ichimoku

### ISSUE THREAD

**Issue by agustin9014** [freqtrade/technical#275]
def ichimoku(
    dataframe, conversion_line_period=9, base_line_periods=26, laggin_span=52, displacement=26
to
def ichimoku(
    dataframe, conversion_line_period=9, base_line_periods=20, laggin_span=60, displacement=120

Ichimoku in the cryptocurrency market
After spending three decades of research and testing, Goichi Hosada, the inventor of the Ichimoku Cloud, decided that the configuration (9, 26, 52) gave the best results. In the past, Japanese business hours started on Saturdays. Thus, the number nine represented one and a half weeks, and the numbers 26 and 52 represented one and two months, respectively.

These setups are still used in many trading contexts. However, for the cryptocurrency markets, traders adjust the Ichimoku settings to reflect the 24/7 markets. The setting therefore changes from (9, 26, 52) to (10, 30,60). Some traders also adjust the setting to (20, 60, 120) in an attempt to minimize false signals.

It is still debated whether it is efficient to modify the configuration. While some traders are convinced that editing the Ichimoku settings is vital, others are concerned that adjusting the settings will upset the balance of the Ichimoku system, producing a large number of invalid signals.

thx

**Comment by xmatthias** [comment]
To be honest - parameters in indicators are something everyone will have a different opinion on.

We'll definitely keep parameters at the default (as originally designed) values - but nothing prevents you (or others) from using different values in your strategy. 
They're arguments for that particular reason - so you can simply pass in the values you desire.

for example: 
``` python
ichis = ichimoku(dataframe, conversion_line_period=9, base_line_periods=20, laggin_span=60, displacement=120)
# ...
```
