### ISSUE TITLE
Multiple timeframe merge 

### ISSUE THREAD

**Issue by SurferAdmin** [freqtrade/technical#283]
I use multiple timeframes in my strategies and I noticed the indicators did not line up with binance charts. The buy/sell signals I saw on the binance charts using the same indicators did not match the signal generated from the bot. 

The cause was:
  Subtract "small" timeframe so merging is not delayed by 1 small candle
  Detailed explanation in https://github.com/freqtrade/freqtrade/issues/4073

**_I have changed the following to resolve my issue, other who might be experiencing similar issue might benefit:_**

**Changed:** 
  resample_merge (/technical/util.py)
  merge_informative_pair(freqtrade/strategy/strategy_helper.py)

**Added:**
raw=False, prefix='primary'

i.e.
  ```def resampled_merge(original: DataFrame, resampled: DataFrame, fill_na=True, raw=False, prefix=''):```

```def merge_informative_pair(dataframe: pd.DataFrame, informative: pd.DataFrame,  timeframe: str, timeframe_inf: str, ffill: bool = True, append_timeframe: bool = True, raw=False, prefix='', date_column: str = 'date') ->pd.DataFrame:```

**Call example:**
  dataframe = resampled_merge_pre(dataframe, primary_timeframe_dataframe, fill_na=True, **raw=True, prefix='primary'**)

**When the "raw" flag is set to True, bypass the logic added due to:**
  Subtract "small" timeframe so merging is not delayed by 1 small candle
  Detailed explanation in https://github.com/freqtrade/freqtrade/issues/4073

**Prefix parameter:**
The "prefix" is a personal choice of using primary, secondary, tertiary, .. instead of 1d, 1h, 15m,.. for code readability and ease of timeframe change. If not set the logic uses the current naming convention. 

I use them as:
  dataframe['primary_open'] 

Instead of:
  dataframe['resample_1d_open']

**Comment by xmatthias** [comment]
Please reformat your post properly (wrap code snippets in tripple backticks (`)).

It's also completely unclear what you're trying to accomplish with this issue - it seems quite messy and some "i did this and then that" - but it's unclear what the actual issue is you're seeing / trying to fix.

**Comment by SurferAdmin** [comment]
> 

No issue, just wanted to point out that dropping one candle (can) impact the signal generated. I had to dig through a lot of data to find the problem. 

I will push my change to the forked repo, it by passes the logic added to drop one candle. Skipping a candle might not have an impact to most use cases. If people notice that the chart buy/sell signal does not match the one from the bot, this might be the culprit.

**Comment by SurferAdmin** [comment]
> > 
> 
> No issue, just wanted to point out that dropping one candle (can) impact the signal generated. I had to dig through a lot of data to find the problem.
> 
> I will push my change to the forked repo. When the raw flag is set it bypasses the logic [freqtrade/freqtrade#4073](https://github.com/freqtrade/freqtrade/issues/4073) which drops one candle.
> 
> Skipping a candle might not impact most use cases. If people notice that the trading view chart buy/sell signal does not match the one from the bot, this might be the culprit.

**Comment by xmatthias** [comment]
"dropping" is not the same as what [#4073 points at](https://github.com/freqtrade/freqtrade/issues/4073) points at.

That's shifting the timeframes so the candle close dates align. Not doing that will delay the signal by 1 minor candle. 
in backtesting - this is not problematic - in live, it'll be, as you'll be using the longer candle not at 00:00 - but only at 00:15 (assuming 15m/1h candles) - which is 15m later than when the candle would've been available.

Please find a detailed explanation of this problem [here](https://github.com/freqtrade/technical/issues/268#issuecomment-1146753500).
It's simply because the dates we work with are candle open dates.
It's not a bug - and nothing that should be optional.

**Comment by SurferAdmin** [comment]
> blematic - in live, it'll

Multiple timeframe are about volatility cascading. The ability to process without shifting resolved my issue and improved the roi significantly to say the least. Let's just keep these as notes for the ones who might be using (any) frequency cascading techniques.

**Comment by xmatthias** [comment]
I don't really understand why you've removed the issue content now.

it's a valid question (this IS a difficult topic) - and a very frequent point of concern.
seeing that binance missaligns (maybe in certain conditions?) may also help other users - would the content have remained.

**Comment by SurferAdmin** [comment]
The issue for me was caused by removal/shifting of the candle in resampled_merge and merge_informative_pair. Not binance. 

You are doing an amazing project to help all, I felt I did not want to get into an argument with you.

**Comment by xmatthias** [comment]
i don't really see it as an argument though - it's a fact that without that logic, the signals will be delayed by 1 minor candle. That's not subjective, but a mathematical fact as we're dealing with candle open dates.

If that's what you desire/need - then you can pretty easily use `pd.merge` directly - without relying on the helper function.

The helper functions are designed to help users merge correctly, without causing delays in their signals. if the delay is intentional - then the helper-functions may not be the correct approach for that strategy.

**Comment by SurferAdmin** [comment]
My 2 cents will be to avoid touching data and let the user manipulate the raw data raw as much as possible. It is mathematically significant in multi frequency cascading, but I agree it might cause users a headache :)

**Comment by SurferAdmin** [comment]
PS. I am super impressed with your responsiveness and diligence!!!

**Comment by xmatthias** [comment]
The fix you're applying is unclear to me (the original issue didn't really show what the precise change was) - but as it's backtesting only - i think you're risking lookahead bias (which will usually show high profits in backtesting - but will then disappoint in live).

now that's not to say this must be the case - but it's a possibility you shouldn't neglect

**Comment by SurferAdmin** [comment]
I found the problem in live run and live data. The change we put in to show the raw candle in Telegram triggered me to dig through the data with a fine comb. I will post you if the live results differ, so far it is working like a charm.

**Comment by SurferAdmin** [comment]
The fix is to add a flag i.e. raw=True which bypasses the following logic in resampled merge & informative merge:

``` if original_int < resampled_int:
        # Subtract "small" timeframe so merging is not delayed by 1 small candle.
        # Detailed explanation in https://github.com/freqtrade/freqtrade/issues/4073
        resampled["date_merge"] = (
            resampled["date"] + to_timedelta(resampled_int, "m") - to_timedelta(original_int, "m")
        ) ```

Plus a cosmetic change to add a variable called prefix='', which the users can use to give the frequency a name like primary, secondary, etc

if prefix != ''
```resampled.columns = [f"{prefix}_{col}" for col in resampled.columns]```
else: (the current naming convention)
```resampled.columns = [f"resample_{resampled_int}_{col}" for col in resampled.columns]```
