### ISSUE TITLE
Laguerre RSI wrong computation

### ISSUE THREAD

**Issue by rd-mg** [freqtrade/technical#290]
I use laguerre RSI from technical to populate_indicators (timeframe=15m) as follows:

        `dataframe['laguerre'] = laguerre(dataframe, gamma=0.75, smooth=1)`

This calculation shows amounts different to any TradingView indicator available

Laguerre RSI compute at the last column

![image](https://user-images.githubusercontent.com/39341114/192067412-05425709-0f9b-4cbd-8b0e-ee0088210832.png)

![image](https://user-images.githubusercontent.com/39341114/192067302-e665d477-737d-40bb-b0a6-edf69c4c9953.png)

Comparing Freqtrade vs TradingView

Date | Time | Technical | TradingView
-- | -- | -- | --
2022-09-23 | 20:15:00+00:00 | 0.613314 | 1
2022-09-23 | 20:30:00+00:00 | 0.650659 | 1
2022-09-23 | 20:45:00+00:00 | 0.627485 | 0.77
2022-09-23 | 21:00:00+00:00 | 0.649085 | 0.53
2022-09-23 | 21:15:00+00:00 | 0.785109 | 0.34
2022-09-23 | 21:30:00+00:00 | 1 | 0.56
2022-09-23 | 21:45:00+00:00 | 1 | 0.73

Comparing the code of Laguerre RSI TradingView (by Kiva) vs Technical, both are very similar but some apparent differences:

1.  Transform gamma by `1-alpha` (line 10), where alpha is the value input by the user, in this case, 0.75
2.  When computing` cu` and `cd` only more than and less than are evaluated, equality is not considered

![image](https://user-images.githubusercontent.com/39341114/192068399-c6c64211-61e8-4152-a215-575966d98c9b.png)

https://github.com/freqtrade/technical/blob/367142a8a0c61d93a5498b85040138e8c835393a/technical/indicators/indicators.py#L87

Could you have a look?

**Comment by xmatthias** [comment]
Using a random, custom indicator from tradingview and claiming that "library X is not aligned to that" is a dangerous approach.

The implementation here aims to mirror the original paper (from John Ehlers - which also has the link in the sourcecode as this: `http://www.davenewberg.com/Trading/TS_Code/Ehlers_Indicators/Laguerre_RSI.html`), which at a first glance, it seems to do.

the tradingview calculation for CU and CD seems to ... quite loosely interpret this (starting from the fact that the comparisons are >, not >=).

**Comment by rd-mg** [comment]
It was certainly a bit rash of me to make such a vague comparison, I'll do a little more digging on it and come back if necessary with some feedback. Thanks for your reply

**Comment by rd-mg** [comment]
I sent the original EHLERS code to Pine Script, certainly, this is good but the default alpha 0.75 doesn't work for me. Alpha = 0.2 has the same result as the popular LRSI I find in TradingView and it has (for me) a better sensitivity to price changes.

I left the comment and images here only for reference maybe someone finds the same situation in the future

I close this issue, thank you @xmatthias 

Alpha = 0.2

![image](https://user-images.githubusercontent.com/39341114/192323920-95975077-2c0f-44de-a722-0d4fb0ddfb9e.png)


Alpha = 0.75

![image](https://user-images.githubusercontent.com/39341114/192323325-6c813620-1896-4e7a-b39e-1f7ea2e48415.png)
