### ISSUE TITLE
utils bug

### ISSUE THREAD

**Issue by Undertoned** [freqtrade/technical#312]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/13451629/215426989-2d3000e0-e5c8-429a-b627-51c49888b876.png">

in line 125:  i guess it should be res_interval not exchange_interval

**Comment by xmatthias** [comment]
nice catch.
Luckily (that's why nobody noticed so far) it's also code that's not used within technical (unless you call it from the outside this way).

all internal usage is with the 2nd parameter as default - which is false, therefore that whole block ain't called.

**Comment by Undertoned** [comment]
> nice catch. Luckily (that's why nobody noticed so far) it's also code that's not used within technical (unless you call it from the outside this way).
> 
> all internal usage is with the 2nd parameter as default - which is false, therefore that whole block ain't called.

Technical has many useful function, and i find it and this mistake, this module help me improve my strategies lot of profit in backtest.
By the way, is there some way or organization,  can  swap some idea on trade strategies,  i find the freqtrade-strategies, but it is more example than experience.  thanks.

**Comment by xmatthias** [comment]
Well freqtrade has a [discord community ](https://discord.gg/p7nuUNVfP7) - where strategies are discussed and sometimes shared.

Now obviously the most profitable strategies are usually not shared publicly ... which is understandable i guess.

**Comment by Undertoned** [comment]
Yes, I know each strategy has its capacity and validity period.  I'm  so beginner and this community is very suitable for me to study.  Thanks for recommend.
