### ISSUE TITLE
resample_to_interval

### ISSUE THREAD

**Issue by blinklabllp** [freqtrade/technical#32]
Hi Wanted to understand how this is implemented and how can I consume this function. 

This is what I am trying to do, any insights will be most appreciated. 

So I want to start a trade based on EMA crossing over 50 going above 200 or 50 going bellow 200 (5m), however, I only want to do Long if ema 50 is over 200 and the price is above ema 50 on (4h) something like that. 

I understand or I think I need to use the function resample_to_interval what does this do? I am passing it the current dataset, of 5m, and telling it to resample it as 15m and then give it back to me as a new data set?

In one of your examples MultiRSI.py, I see this implemented. And I also see the data is again remerged with resampled_merge, what is the need for that? When the resampling occurs are you resampling the dataset sent directly or creating a copy and giving it back to me. 

Thanks any help would be appriciated.

Here is my custom stratagy
`
        def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                from technical.util import resample_to_interval
                from technical.util import resampled_merge
        
        # Custom code for sampling data on higher TF
        dataframe_htf = resample_to_interval(dataframe, self.cust_ticker_interval)

        #Get MACD values of both time frame 
        
        macd = ta.MACD(dataframe)
        dataframe['macd'] = macd['macd']
        dataframe['macdsignal'] = macd['macdsignal']
        dataframe['macdhist'] = macd['macdhist']

        macd = ta.MACD(dataframe_htf)
        dataframe['macd_htf'] = macd['macd']
        dataframe['macdsignal_htf'] = macd['macdsignal']
        dataframe['macdhist_htf'] = macd['macdhist']

        # RSI 
        dataframe['rsi'] = ta.RSI(dataframe)
        dataframe['rsi_htf'] = ta.RSI(dataframe_htf)

        # EMA - Exponential Moving Average """
        dataframe['ema8'] = ta.EMA(dataframe, timeperiod=8)
        dataframe['ema13'] = ta.EMA(dataframe, timeperiod=13)
        dataframe['ema21'] = ta.EMA(dataframe, timeperiod=21)
        dataframe['ema55'] = ta.EMA(dataframe, timeperiod=55)
        dataframe['ema120'] = ta.EMA(dataframe, timeperiod=120)
        dataframe['ema233'] = ta.EMA(dataframe, timeperiod=233)

        # EMA - Exponential Moving Average """
        dataframe['ema55_htf'] = ta.EMA(dataframe_htf, timeperiod=55)
        dataframe['ema120_htf'] = ta.EMA(dataframe_htf, timeperiod=120)
        dataframe['ema233_htf'] = ta.EMA(dataframe_htf, timeperiod=233)
        

`

**Comment by xmatthias** [comment]
Your issue is this:
```
    # EMA - Exponential Moving Average """
    dataframe['ema55_htf'] = ta.EMA(dataframe_htf, timeperiod=55)
    dataframe['ema120_htf'] = ta.EMA(dataframe_htf, timeperiod=120)
    dataframe['ema233_htf'] = ta.EMA(dataframe_htf, timeperiod=233)
```

you assign the EMA of the resampled timeframe to the non-resampled, which is a much longer dataframe, so the values don't match and are in the wrong position.

Assign all values for the resampled timeframe to `dataframe_htf` and merge them after that (which you already do, based on the strategy shared on slack).

The merge-statement will change the name slightly (in your case, you'll need to compare `(dataframe['resample_240_ema55_htf'] > dataframe['ema233']) &`)...

**Comment by hroff-1902** [comment]
@blinklabllp here is how to insert code fragments into github issues properly (for readability): https://help.github.com/en/articles/creating-and-highlighting-code-blocks#fenced-code-blocks

I cannot edit the other's posts at this repo...

**Comment by blinklabllp** [comment]
Thanks for the info, I have tired to fix the code post above. 

Also now when I merge it back, I will be able to access the dataframe['resample_240_ema55_htf']  in the order calls?

**Comment by xmatthias** [comment]
well yes - but the name will depend on the resample interval (the `240` in that stands for the minutes you resampled to, so 4 * 60 for 4h intervals).

**Comment by blinklabllp** [comment]
Gotcha, thanks a lot helping me out.
