### ISSUE TITLE
Help needed with: AttributeError: 'SSL' object has no attribute 'copy'

### ISSUE THREAD

**Issue by sandervdhave** [freqtrade/technical#378]
Operating system: Ventura 13.4.1
Python Version: 3.11
CCXT version: 3.1.44
Freqtrade Version: freqtrade docker-2023.6.dev-c5510491

I am building a strategy with the SSLChannels from indicators.py. But i keep getting this error:

`
2023-10-25 20:20:18,748 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/freqtrade/freqtrade/main.py", line 42, in main
    return_code = args['func'](args)
                  ^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/commands/optimize_commands.py", line 58, in start_backtesting
    backtesting.start()
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1357, in start
    min_date, max_date = self.backtest_one_strategy(strat, data, timerange)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/optimize/backtesting.py", line 1275, in backtest_one_strategy
    preprocessed = self.strategy.advise_all_indicators(data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1321, in advise_all_indicators
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1321, in <dictcomp>
    return {pair: self.advise_indicators(pair_data.copy(), {'pair': pair}).copy()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/freqtrade/strategy/interface.py", line 1339, in advise_indicators
    return self.populate_indicators(dataframe, metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/user_data/strategies/ssl.py", line 68, in populate_indicators
    dataframe['sslDown'], dataframe['sslUp'] = self.SSLChannels(length=10)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/freqtrade/user_data/strategies/ssl.py", line 48, in SSLChannels
    df = dataframe.copy()
         ^^^^^^^^^^^^^^
AttributeError: 'SSL' object has no attribute 'copy'
`

I have searched everywhere, but could not find any solution. This is my code:

`
# --- Do not remove these libs ---
import numpy as np  # noqa
import pandas as pd  # noqa
from pandas import DataFrame
from typing import Optional, Union

from freqtrade.strategy import (BooleanParameter, CategoricalParameter, DecimalParameter,
                                IStrategy, IntParameter)

# --------------------------------
# Add your lib to import here
import talib.abstract as ta
import freqtrade.vendor.qtpylib.indicators as qtpylib

'''
freqtrade backtesting --config user_data/config.json --strategy SSL --timeframe 5m --timerange 20230101- --pairs BTC/USDT:USDT
freqtrade plot-dataframe --config user_data/config.json --strategy SSL --timeframe 5m --timerange 20230101- --pairs BTC/USDT:USDT
'''

# This class is a sample. Feel free to customize it.
class SSL(IStrategy):
    INTERFACE_VERSION = 3

    can_short: bool = True

    minimal_roi = {
        "0": 0.06
    }

    stoploss = -0.02

    # Plot
    plot_config = {
        'main_plot': {
            'ema200': {'color': 'blue'},
            'sslUp': {'color': 'green'},
            'sslDown': {'color': 'red'},
        }
    }

    def SSLChannels(dataframe, length=10, mode="sma"):
        if mode not in ("sma",):
            raise ValueError(f"Mode {mode} not supported yet")

        df = dataframe.copy()

        if mode == "sma":
            df["smaHigh"] = df["high"].rolling(length).mean()
            df["smaLow"] = df["low"].rolling(length).mean()

        df["hlv"] = np.where(
            df["close"] > df["smaHigh"], 1, np.where(df["close"] < df["smaLow"], -1, np.NAN)
        )
        df["hlv"] = df["hlv"].ffill()

        df["sslDown"] = np.where(df["hlv"] < 0, df["smaHigh"], df["smaLow"])
        df["sslUp"] = np.where(df["hlv"] < 0, df["smaLow"], df["smaHigh"])

        print (df)
        return df["sslDown"], df["sslUp"]

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

        dataframe['ema200'] = ta.EMA(dataframe, timeperiod=200)
        dataframe['sslDown'], dataframe['sslUp'] = self.SSLChannels(length=10)
        print (dataframe)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['sslDown'], dataframe['sslUp'])) &
                (dataframe['close'] > dataframe['ema200']) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'enter_long'] = 1

        dataframe.loc[
            (
                (qtpylib.crossed_above(dataframe['sslUp'], dataframe['sslDown'])) &
                (dataframe['close'] < dataframe['ema200']) &
                (dataframe['volume'] > 0)  # Make sure Volume is not 0
            ),
            'enter_short'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # Never sells
        dataframe.loc[:, 'exit_long'] = 0
        
        # Never sells
        dataframe.loc[:, 'exit_short'] = 0
        
        return dataframe
`

Can anyone help?

**Comment by stash86** [comment]
You are calling the SSL function incorrectly. First, don't need to use `self.`. Second, you don't give the required dataframe.

**Comment by stash86** [comment]
Reading material

https://botacademy.ddns.net/2023/10/19/fsd-custom-indicators-part-2/

**Comment by sandervdhave** [comment]
That's great! Thanks, it's working. And thank you for the fast reply.
