### ISSUE TITLE
A few Pinescript lines

### ISSUE THREAD

**Issue by kookic** [freqtrade/technical#427]
Hello, I need your help because I cannot convert and use this Pinescript code in my Freqtrade strategy.
ta.highestbars is my problem! TV return number hbar from 0 to -CalcPeriod 
If anyone has a solution, thank you very much.

The part indicator of the pinescript I want to use:
	
float CalcPrice  = "Source"
int CalcPeriod   = 30  
float prices = ta.ema("close", 8)
int hbar = ta.highestbars(prices, CalcPeriod)
float hval = nz(CalcPrice[math.abs(hbar)])
int lbar = ta.lowestbars(prices, CalcPeriod)
float lval = nz(CalcPrice[math.abs(lbar)])

**Comment by xmatthias** [comment]
well even after looking at the pinescript manual - i'm not sure what `highestbars()` is supposed to show / do.

From the name - i'd suspect it's something around `dataframe['ema'].rolling().max()` - but the description says "offset to highest bar" - which i assume will be something around `dataframe['ema'].rolling().max() - dataframe['ema']` (using close as your code provides the ema as "prices").

However,  i'm absolutely uncertain about this (the main problem here is that i don't understand the pinescript manual).

Hope this gets you started in the right direction.

Actual conversations from pinescript to python are however often problematic - and is not something we'll provide actual help or support with.

**Comment by kookic** [comment]
Thank you very much, I agree, I will drop the matter.
