### ISSUE TITLE
Ichimoku indicator

### ISSUE THREAD

**Issue by sidnicholas** [freqtrade/technical#52]
I am interested in using the Ichimoku indicator but it looks like it's not yet available in the package.  Do you know when it will be available?

Also, I am novice at python.  I know how to figure things out but I'm sure it takes me quite a bit longer to resolve issues than it does most developers.  You mentioned that you would like to some help with adding more indicators.  It's something I would like to help with although I am sure I would need some guidance.

Thanks

**Comment by berlinguyinca** [comment]
Has been in there forever

**Comment by hroff-1902** [comment]
https://github.com/freqtrade/technical/blob/57ee5d001b922b883fb2fea8aa29101faf6cb037/technical/indicators.py#L670-L708

**Comment by sidnicholas** [comment]
Thanks!  Let me know if there's anything I can do to help move things along.
