### ISSUE TITLE
Memory leak problem in Ichimoku Indicator.

### ISSUE THREAD

**Issue by Superior18** [freqtrade/technical#69]
Memory usage will increase until it reaches 100%.
This is happening slowly. For example, it will increase by 15% every 10 minutes.
This problem causes the robot to be automatically killed by the operating system after about 45 minutes.
My strategy :
```
# --- Do not remove these libs ---
from freqtrade.strategy.interface import IStrategy
from typing import Dict, List
from functools import reduce
from pandas import DataFrame
# --------------------------------
import technical.indicators as ta


class icu(IStrategy):
    """

    author@: Gert Wohlgemuth

    idea:

        uptrend definition:
            MACD above MACD signal
            and CCI < -50

        downtrend definition:
            MACD below MACD signal
            and CCI > 100

    """

    # Minimal ROI designed for the strategy.
    # This attribute will be overridden if the config file contains "minimal_roi"
    minimal_roi = {
        "120":  0.03,
        "60":  0.06,
        "40":  0.08,
        "20":  0.1
    }

    # Optimal stoploss designed for the strategy
    # This attribute will be overridden if the config file contains "stoploss"
    stoploss = -0.1
    order_types = {
    "buy": "limit",
    "sell": "limit",
    "emergencysell": "market",
    "stoploss": "market",
    "stoploss_on_exchange": False,
    "stoploss_on_exchange_interval": 60,
    "stoploss_on_exchange_limit_ratio": 0.99,
    }
    # Optimal ticker interval for the strategy
    ticker_interval = '5m'

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # ichimoku
        ichi = ta.ichimoku(dataframe)
        dataframe['tenkan']=ichi['tenkan_sen']
        dataframe['kijun']=ichi['kijun_sen']
        dataframe['senkou_a']=ichi['senkou_span_a']
        dataframe['senkou_b']=ichi['senkou_span_b']
        dataframe['cloud_green']=ichi['cloud_green']
        dataframe['cloud_red']=ichi['cloud_red']

        return dataframe

    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
                (dataframe['tenkan'].shift(1)<dataframe['kijun'].shift(1)) &
                (dataframe['tenkan']>dataframe['kijun'])
                (dataframe['cloud_red']==True)
            ),
            'buy'] = 1
        return dataframe

    def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[
            (
            ),
            'sell'] = 1
        return dataframe

```

**Comment by xmatthias** [comment]
there's not much information in this issue to be honest...

First of all, which version of freqtrade are you using? on which operating system, and with which version of Python?

Also, what's the total memory you've got on your system?
What command are you running (trade, backtesting, hyperopt, ...)?

**Comment by Superior18** [comment]
freqtrade Version : freqtrade develop-39ea126
python version : Python 3.8.2 (also tested with python 3.6.9 and get same result in memory usage)
OS : Debian 8 32 bit version.
physical system memory 2 GB.
freqtrade command : freqtrade trade

**Comment by xmatthias** [comment]
just to understand this right -  by only using ichimoku (as shown in the above sample), you're experiencing a memory leak ... 

but when using ichimoku from FinTA it's fine... ?

**Comment by Superior18** [comment]
Yes. Exactly so.
It seems that in the technical module, the Ichimoku indicator has a problem and creates a memory leak.

**Comment by xmatthias** [comment]
Am i correct in assuming that the missing ampersand in line 67 (2nd line of the buy condition) is just a typo and in reality you're not seeing any errors on the console?

**Comment by xmatthias** [comment]
Since pandas 1.0.4 was released, this should no longer be a problem.

It's now a dependency for both freqtrade (master / develop) and for the technical repository.
