### ISSUE TITLE
MOST indicator   

### ISSUE THREAD

**Issue by tarantula3535** [freqtrade/technical#90]
i am work to write this indicator....   
https://tr.tradingview.com/v/28ZcW4nv/  MOST by Anıl ÖZEKŞİ
actually good filtering buy or sell ... her is the  code... 
my problem is 
so slow the backtesting. where is the wrong or why my codes are so slow in the backtesting?

``` python
def MOST(dataframe , percent, length):
    import talib.abstract as ta
    emacol = 'ema_' + str(length) + '_' + str(percent)
    mostcol = 'most_' + str(length) + '_' + str(percent)
    dataframe[emacol] = ta.EMA( dataframe , timeperiod = length)
    dataframe[emacol] = dataframe[emacol].fillna(method="bfill")
    dataframe['tempema'] = 0.000000
    dataframe['trend'] = -1
    dataframe[mostcol] = 0.000000
    for i in range(1,len(dataframe[emacol])):
        if (dataframe['trend'][i-1] == 1) & (dataframe['tempema'][i-1] >= dataframe[emacol][i]):
            dataframe.loc[i,'tempema'] = dataframe.loc[i-1,'tempema']
        elif (dataframe['trend'][i-1] == 1) & (dataframe['tempema'][i-1] < dataframe[emacol][i]):
            dataframe.loc[i,'tempema'] = dataframe.loc[i,emacol]
        elif (dataframe['trend'][i-1] == -1) & (dataframe['tempema'][i-1] <= dataframe[emacol][i]):
            dataframe.loc[i,'tempema'] = dataframe.loc[i-1,'tempema']
        elif (dataframe['trend'][i-1] == -1) & (dataframe['tempema'][i-1] > dataframe[emacol][i]):
            dataframe.loc[i,'tempema'] = dataframe.loc[i,emacol]
        
        if (dataframe[emacol][i] >= dataframe[mostcol][i-1]) & (dataframe['trend'][i-1] == 1):
            dataframe.loc[i,'trend'] = 1
            dataframe.loc[i,mostcol] = dataframe['tempema'][i]*(1-percent)
        elif (dataframe[emacol][i] <= dataframe[mostcol][i-1]) & (dataframe['trend'][i-1] == -1):
            dataframe.loc[i,'trend'] = -1
            dataframe.loc[i,mostcol] = dataframe['tempema'][i]*(1+percent)
        elif (dataframe[emacol][i] >= dataframe[mostcol][i-1]) & (dataframe['trend'][i-1] == -1):
            dataframe.loc[i,'trend'] = 1
            dataframe.loc[i,mostcol] = dataframe['tempema'][i]*(1-percent)
        elif (dataframe[emacol][i] <= dataframe[mostcol][i-1]) & (dataframe['trend'][i-1] == 1):
            dataframe.loc[i,'trend'] = -1
            dataframe.loc[i,mostcol] = dataframe['tempema'][i]*(1+percent)
    return {
        emacol : dataframe[emacol] ,
        mostcol : dataframe[mostcol]
    }

```

**Comment by tarantula3535** [comment]
i find a bug in this code.. and recalculate like Supertrende and got the same result in the Tradingview..
here is the update
`def MOST2(dataframe,  percent=2, length=8, MAtype=1):
    """
    Function to compute MOST
    
    Args :
        df : Pandas DataFrame which contains ['date', 'open', 'high', 'low', 'close', 'volume'] columns
        period : Integer indicates the period of computation in terms of number of candles
        multiplier : Integer indicates value to multiply the ATR
        ohlc: List defining OHLC Column names (default ['Open', 'High', 'Low', 'Close'])
        
    Returns :
        df : Pandas DataFrame with new columns added for 
            True Range (TR), ATR (ATR_$period)
            SuperTrend (ST_$period_$multiplier)
            SuperTrend Direction (STX_$period_$multiplier)
    """
    import talib.abstract as ta
    df = dataframe.copy()
    mostvalue = 'MOST_' + str(length) + '_' + str(percent)
    mavalue = 'MA_' + str(length) + '_' + str(percent) 
    trend = 'Trend_' + str(length) + '_' + str(percent)
    """
    atrtype==1 --> EMA
    atrtype==2 --> DEMA
    atrtype==3 --> T3
    """
    # Compute basic upper and lower bands
    if MAtype==1:
        df[mavalue]=ta.EMA(df , timeperiod = length)
    elif MAtype==2:
        df[mavalue]=ta.DEMA(df , timeperiod = length)
    elif MAtype==3:
        df[mavalue]=ta.T3(df , timeperiod = length)
    df['basic_ub'] = df[mavalue] * (1+percent/100)
    df['basic_lb'] = df[mavalue] * (1-percent/100)
    # Compute final upper and lower bands
    df['final_ub'] = 0.00
    df['final_lb'] = 0.00
    for i in range(length, len(df)):
        df['final_ub'].iat[i] = df['basic_ub'].iat[i] if df['basic_ub'].iat[i] < df['final_ub'].iat[i - 1] or df[mavalue].iat[i - 1] > df['final_ub'].iat[i - 1] else df['final_ub'].iat[i - 1]
        df['final_lb'].iat[i] = df['basic_lb'].iat[i] if df['basic_lb'].iat[i] > df['final_lb'].iat[i - 1] or df[mavalue].iat[i - 1] < df['final_lb'].iat[i - 1] else df['final_lb'].iat[i - 1]
       
    # Set the MOST value
    df[mostvalue] = 0.00
    for i in range(length, len(df)):
        df[mostvalue].iat[i] = df['final_ub'].iat[i] if df[mostvalue].iat[i - 1] == df['final_ub'].iat[i - 1] and df[mavalue].iat[i] <= df['final_ub'].iat[i] else \
                        df['final_lb'].iat[i] if df[mostvalue].iat[i - 1] == df['final_ub'].iat[i - 1] and df[mavalue].iat[i] >  df['final_ub'].iat[i] else \
                        df['final_lb'].iat[i] if df[mostvalue].iat[i - 1] == df['final_lb'].iat[i - 1] and df[mavalue].iat[i] >= df['final_lb'].iat[i] else \
                        df['final_ub'].iat[i] if df[mostvalue].iat[i - 1] == df['final_lb'].iat[i - 1] and df[mavalue].iat[i] <  df['final_lb'].iat[i] else 0.00             
    # Mark the trend direction up/down
    df[trend] = np.where((df[mostvalue] > 0.00), np.where((df[mavalue] < df[mostvalue]), 'down',  'up'), np.NaN)
    # Remove basic and final bands from the columns
    df.drop(['basic_ub', 'basic_lb', 'final_ub', 'final_lb'], inplace=True, axis=1)    
    df.fillna(0, inplace=True)
    return df    
`

**Comment by tarantula3535** [comment]
i find a bug this code and recalculate it..now same results in the tradingviews
`def MOST2(dataframe,  percent=2, length=8, MAtype=1):
    import talib.abstract as ta
    df = dataframe.copy()
    mostvalue = 'MOST_' + str(length) + '_' + str(percent)
    mavalue = 'MA_' + str(length) + '_' + str(percent) 
    trend = 'Trend_' + str(length) + '_' + str(percent)
    # MAtype==1 --> EMA
    # MAtype==2 --> DEMA
    # MAtype==3 --> T3
    # Compute basic upper and lower bands
    if MAtype==1:
        df[mavalue]=ta.EMA(df , timeperiod = length)
    elif MAtype==2:
        df[mavalue]=ta.DEMA(df , timeperiod = length)
    elif MAtype==3:
        df[mavalue]=ta.T3(df , timeperiod = length)
    df['basic_ub'] = df[mavalue] * (1+percent/100)
    df['basic_lb'] = df[mavalue] * (1-percent/100)
    # Compute final upper and lower bands
    df['final_ub'] = 0.00
    df['final_lb'] = 0.00
    for i in range(length, len(df)):
        df['final_ub'].iat[i] = df['basic_ub'].iat[i] if df['basic_ub'].iat[i] < df['final_ub'].iat[i - 1] or df[mavalue].iat[i - 1] > df['final_ub'].iat[i - 1] else df['final_ub'].iat[i - 1]
        df['final_lb'].iat[i] = df['basic_lb'].iat[i] if df['basic_lb'].iat[i] > df['final_lb'].iat[i - 1] or df[mavalue].iat[i - 1] < df['final_lb'].iat[i - 1] else df['final_lb'].iat[i - 1]     
    # Set the MOST value
    df[mostvalue] = 0.00
    for i in range(length, len(df)):
        df[mostvalue].iat[i] = df['final_ub'].iat[i] if df[mostvalue].iat[i - 1] == df['final_ub'].iat[i - 1] and df[mavalue].iat[i] <= df['final_ub'].iat[i] else \
                        df['final_lb'].iat[i] if df[mostvalue].iat[i - 1] == df['final_ub'].iat[i - 1] and df[mavalue].iat[i] >  df['final_ub'].iat[i] else \
                        df['final_lb'].iat[i] if df[mostvalue].iat[i - 1] == df['final_lb'].iat[i - 1] and df[mavalue].iat[i] >= df['final_lb'].iat[i] else \
                        df['final_ub'].iat[i] if df[mostvalue].iat[i - 1] == df['final_lb'].iat[i - 1] and df[mavalue].iat[i] <  df['final_lb'].iat[i] else 0.00             
    # Mark the trend direction up/down
    df[trend] = np.where((df[mostvalue] > 0.00), np.where((df[mavalue] < df[mostvalue]), 'down',  'up'), np.NaN)
    # Remove basic and final bands from the columns
    df.drop(['basic_ub', 'basic_lb', 'final_ub', 'final_lb'], inplace=True, axis=1)    
    df.fillna(0, inplace=True)
    return df    
`

**Comment by tarantula3535** [comment]
`def MOST2(dataframe,  percent=2, length=8, MAtype=1):
    import talib.abstract as ta
    df = dataframe.copy()
    mostvalue = 'MOST_' + str(length) + '_' + str(percent)
    mavalue = 'MA_' + str(length) + '_' + str(percent)
    trend = 'Trend_' + str(length) + '_' + str(percent)
    # MAtype==1 --> EMA
    # MAtype==2 --> DEMA
    # MAtype==3 --> T3
    # Compute basic upper and lower bands
    if MAtype==1:
        df[mavalue]=ta.EMA(df , timeperiod = length)
    elif MAtype==2:
        df[mavalue]=ta.DEMA(df , timeperiod = length)
    elif MAtype==3:
        df[mavalue]=ta.T3(df , timeperiod = length)
    df['basic_ub'] = df[mavalue] * (1+percent/100)
    df['basic_lb'] = df[mavalue] * (1-percent/100)
    # Compute final upper and lower bands
    df['final_ub'] = 0.00
    df['final_lb'] = 0.00
    for i in range(length, len(df)):
        df['final_ub'].iat[i] = df['basic_ub'].iat[i] if df['basic_ub'].iat[i] < df['final_ub'].iat[i - 1] or df[mavalue].iat[i - 1] > df['final_ub'].iat[i - 1] else df['final_ub'].iat[i - 1]
        df['final_lb'].iat[i] = df['basic_lb'].iat[i] if df['basic_lb'].iat[i] > df['final_lb'].iat[i - 1] or df[mavalue].iat[i - 1] < df['final_lb'].iat[i - 1] else df['final_lb'].iat[i - 1]
    # Set the MOST value
    df[mostvalue] = 0.00
    for i in range(length, len(df)):
        df[mostvalue].iat[i] = df['final_ub'].iat[i] if df[mostvalue].iat[i - 1] == df['final_ub'].iat[i - 1] and df[mavalue].iat[i] <= df['final_ub'].iat[i] else \
                        df['final_lb'].iat[i] if df[mostvalue].iat[i - 1] == df['final_ub'].iat[i - 1] and df[mavalue].iat[i] >  df['final_ub'].iat[i] else \
                        df['final_lb'].iat[i] if df[mostvalue].iat[i - 1] == df['final_lb'].iat[i - 1] and df[mavalue].iat[i] >= df['final_lb'].iat[i] else \
                        df['final_ub'].iat[i] if df[mostvalue].iat[i - 1] == df['final_lb'].iat[i - 1] and df[mavalue].iat[i] <  df['final_lb'].iat[i] else 0.00
    # Mark the trend direction up/down
    df[trend] = np.where((df[mostvalue] > 0.00), np.where((df[mavalue] < df[mostvalue]), 'down',  'up'), np.NaN)
    # Remove basic and final bands from the columns
    df.drop(['basic_ub', 'basic_lb', 'final_ub', 'final_lb'], inplace=True, axis=1)
    df.fillna(0, inplace=True)
    return df
`

**Comment by hroff-1902** [comment]
is it explained anywhere else, beside that page at tradingview?

**Comment by tarantula3535** [comment]
yes..
[http://teknikanalizsanati.com/pagesorgulama.aspx?bolum=MOST&sayfano=3&kategoriSira=84](url)

**Comment by hroff-1902** [comment]
The text there is placed there as a picture, untranslatable with an online translator, to get the description in English...

The code in tradingview is closed non-public, are you sure you do not violate copyright of the author of it rewriting it in python?

**Comment by tarantula3535** [comment]
yes i write publisher Anil Özekşi on twitter.. only with the condition that we publish the indicator name is "MOST"

**Comment by hroff-1902** [comment]
* the permission to use should be public
* the problem with this indicator is that the description is in Turkish language, is not described anywhere else, and is posted as a picture, so I cannot even use an online translator to translate and understand the idea/verify the implementation.

For the sake of analogy, in Wikipedia terms, I would say it falls into the "original research" (https://en.wikipedia.org/wiki/Wikipedia:No_original_research) category -- an indicator which is only described in one (or a few) article by its creator and not used anywhere else...

**Comment by equinox794** [comment]
line 30, in MOST2
    df = dataframe.copy()
AttributeError: 'float' object has no attribute 'copy'

**Comment by xmatthias** [comment]
well you're not calling the indicator correctly. 
it should be `MOST2(dataframe, <parameters>)` - and it seems like you're missing the dataframe parameter.

**Comment by equinox794** [comment]
thanks for answer 
```

klines = client.get_klines(symbol=symbol, interval=Client.KLINE_INTERVAL_5MINUTE)
klines = df(klines)
test =  MOST2(klines,  percent=2, length=8, MAtype=1)
print(test)
```
Traceback (most recent call last):
  File "d:\p\most2.py", line 64, in <module>
    b = MOST2(klines,  percent=2, length=8, MAtype=1)
  File "d:\p\most2.py", line 35, in MOST2
    df[mavalue]=ta.EMA(df , timeperiod = length)
  File "_abstract.pxi", line 398, in talib._ta_lib.Function.__call__
  File "_abstract.pxi", line 270, in talib._ta_lib.Function.set_function_args
  File "_abstract.pxi", line 221, in talib._ta_lib.Function.set_input_arrays
Exception: input_arrays parameter missing required data key: close

**Comment by xmatthias** [comment]
The whole technical library is intended to be used with freqtrade - or with a dataframe formatted as such.
which means, the following keys are requried:
`["date", "open", "high", "low", "close"]`.

Not all indicators will use all columns - but to be on the safe side, best have all of them available.

**Comment by equinox794** [comment]
date               open        high         low        close
0    1614265800000  1634.37  1637.93  1633.43  1634.14
1    1614266100000  1634.15  1640.72  1633.80  1638.64
2    1614266400000  1638.63  1644.02  1635.67  1636.31
3    1614266700000  1636.47  1638.20  1626.41  1626.45
4    1614267000000  1626.42  1631.79  1624.35  1624.84
..             ...      ...      ...      ...      ...
495  1614414300000  1470.94  1474.19  1461.94  1466.48
496  1614414600000  1466.48  1473.55  1461.50  1473.06
497  1614414900000  1473.20  1475.61  1469.64  1473.55
498  1614415200000  1473.80  1475.33  1470.00  1473.00
499  1614415500000  1473.16  1475.95  1466.65  1474.92

[500 rows x 5 columns]
Traceback (most recent call last):
  File "most2.py", line 74, in <module>
    test = MOST2(klines,  percent=2, length=8, MAtype=1)
  File "d:\p\most2.py", line 45, in MOST2
    df[mavalue]=ta.EMA(df , timeperiod = length)
  File "_abstract.pxi", line 398, in talib._ta_lib.Function.__call__
  File "_abstract.pxi", line 270, in talib._ta_lib.Function.set_function_args
  File "_abstract.pxi", line 221, in talib._ta_lib.Function.set_input_arrays
Exception: input_arrays parameter missing required data key: close
